### ISSUE TITLE
Can't mount

### ISSUE THREAD

**Issue by Foul** [dakhnod/fzfs#1]
foul@Foulnux:/mnt/2To/home/Hack/Flipper_Zero/fzfs$ python3 -m venv venv
foul@Foulnux:/mnt/2To/home/Hack/Flipper_Zero/fzfs$ . venv/bin/activate
(venv) foul@Foulnux:/mnt/2To/home/Hack/Flipper_Zero/fzfs$ venv/bin/python3 fzfs.py /dev/ttyACM0 /mnt/2To/Tmp/
Traceback (most recent call last):
  File "fzfs.py", line 6, in <module>
    import flipper_api
  File "/mnt/2To/home/Hack/Flipper_Zero/fzfs/flipper_api.py", line 7, in <module>
    from flipperzero_protobuf_py.flipperzero_protobuf_compiled import application_pb2, flipper_pb2, storage_pb2
ModuleNotFoundError: No module named 'flipperzero_protobuf_py.flipperzero_protobuf_compiled'
(venv) foul@Foulnux:/mnt/2To/home/Hack/Flipper_Zero/fzfs$ 

folder "flipperzero_protobuf_py" empty when cloning/downloading

**Comment by dakhnod** [comment]
That is really weird. Did you use the --recursive flag when cloning?

**Comment by Foul** [comment]
i just follow the doc... point by point..

git clone --recursive [git@github.com](mailto:git@github.com):dakhnod/fzfs.git (ssh: connect to host github.com port 22000: Connection timed out)

git clone --recursive https://github.com/dakhnod/fzfs.git (ssh: connect to host github.com port 22000: Connection timed out)

**Comment by paletochen** [comment]
I had this problem using the https address to clone (including --recursive) but it worked when i used the ssh connection to clone the repo.
So it seems that something is missing when you clone using the https connection

**Comment by dakhnod** [comment]
Very weird, for me both work recursively. Could you try on another computer?

**Comment by dakhnod** [comment]
I've updated the README instructions to clone using https. That should not require an SSH key. Still, something about your setup seems weird...

**Comment by Foul** [comment]
Still @work, not better sorry : 

foul@Fouldis:~/Téléchargements/FLIPPER$ git clone --recursive https://github.com/dakhnod/fzfs.git
Clonage dans 'fzfs'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 34 (delta 16), reused 25 (delta 10), pack-reused 0
Dépaquetage des objets: 100% (34/34), 9.18 Kio | 447.00 Kio/s, fait.
Sous-module 'flipperzero_protobuf_py' (git@github.com:flipperdevices/flipperzero_protobuf_py.git) enregistré pour le chemin 'flipperzero_protobuf_py'
Clonage dans '/home/foul/Téléchargements/FLIPPER/fzfs/flipperzero_protobuf_py'...
git@github.com: Permission denied (publickey).
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
fatal: le clonage de 'git@github.com:flipperdevices/flipperzero_protobuf_py.git' dans le chemin de sous-module '/home/foul/Téléchargements/FLIPPER/fzfs/flipperzero_protobuf_py' a échoué
Impossible de cloner 'flipperzero_protobuf_py'. Réessai prévu
Clonage dans '/home/foul/Téléchargements/FLIPPER/fzfs/flipperzero_protobuf_py'...
git@github.com: Permission denied (publickey).
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
fatal: le clonage de 'git@github.com:flipperdevices/flipperzero_protobuf_py.git' dans le chemin de sous-module '/home/foul/Téléchargements/FLIPPER/fzfs/flipperzero_protobuf_py' a échoué
Impossible de cloner 'flipperzero_protobuf_py' pour la seconde fois, abandon
foul@Fouldis:~/Téléchargements/FLIPPER$

**Comment by Foul** [comment]
Working now 👍🏻
thx.
