### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by Incongruous2358** [dakhnod/fzfs#11]
![image_2024-10-27_030426072](https://github.com/user-attachments/assets/fd7674e8-6eae-4a0c-a03c-3131cd51a47e)
This error pops up when I try installing the driver.

**Comment by dakhnod** [comment]
Shouldn't you do this in a shell like bash or zsh, not in the interpreter?

**Comment by Incongruous2358** [comment]
I know absolutely nothing about python lol but i tried it in multiple places this is on a different computer here
![image](https://github.com/user-attachments/assets/d8a46c99-5fa5-4324-ad87-d1463755c49e)
![image](https://github.com/user-attachments/assets/572ff313-2f42-4e8e-8986-cc7ea90a9925)

**Comment by dakhnod** [comment]
Do not do this in a python REPL. Do this in Powershell or bash

**Comment by Incongruous2358** [comment]
![image](https://github.com/user-attachments/assets/55769890-9985-49d5-85a4-7fd3cb860b3a)

**Comment by dakhnod** [comment]
Do not enter `python` before entering the commands. By entering `python` you enter the REPL.

**Comment by Incongruous2358** [comment]
![image](https://github.com/user-attachments/assets/bdb7a747-eef6-44b2-b6ac-b9bc86d6ec47)

**Comment by dakhnod** [comment]
Wait, windows doesn't have fuse anyways, AFAIK. This will not work, probably. If you still want to try, check the syntax for pip unter windows

**Comment by Incongruous2358** [comment]
Thank you for your help, I hope you have a wonderful rest of your day.
